### ISSUE TITLE
arrow-parens linting error

### ISSUE THREAD

**Issue by ArmaanAS** [eslint-stylistic/eslint-stylistic#57] opened 2023-11-09 18:19 UTC
/js/arrow-parens rule causes lint to error on an arrow function assignment, e.g. `const x = (a) => 1;`

```JSON
"rules": {
    "@stylistic/js/arrow-parens": ["warn", "as-needed"]
}
```

JS examples of failure

```javascript
const x = (a) => 1;
const xx = a => 1;
```

Error message
```md
Oops! Something went wrong! :(

ESLint: 8.19.0

TypeError: Cannot read properties of undefined (reading 'getTokenBefore')
Occurred while linting /project/test.js:1
Rule: "@stylistic/js/arrow-parens"
    at findOpeningParenOfParams (/project/node_modules/@stylistic/eslint-plugin-js/dist/arrow-parens.js:84:44)
    at ArrowFunctionExpression[params.length=1] (/project/node_modules/@stylistic/eslint-plugin-js/dist/arrow-parens.js:135:30)
    at ruleErrorHandler (/project/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

**Comment by antfu** [comment] 2023-11-09 18:21
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-09 18:21 UTC
