### ISSUE TITLE
Maximum call stack exceeded when using colon in property names e.g onSetup:context

### ISSUE THREAD

**Issue by andtii** [eslint-stylistic/eslint-stylistic#23] opened 2023-10-20 11:27 UTC
when using "@stylistic/indent": ["error", 2] the rule crashes when having colons in the property names with is common for vue3 e.g onUpdate:state={}

![image](https://github.com/eslint-stylistic/eslint-stylistic/assets/1434571/ffd96f0e-8500-483a-8d87-f93af8796dff)

**Comment by antfu** [comment] 2023-10-31 17:44
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-31 17:44 UTC
