### ISSUE TITLE
jsx stylistic dont working properly in script tag 

### ISSUE THREAD

**Issue by TheElegantCoding** [eslint-stylistic/eslint-stylistic#210] opened 2023-12-05 18:18 UTC
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

this is an astro file and jsx rules are not working correctly here in the script tag

![image](https://github.com/eslint-stylistic/eslint-stylistic/assets/70770072/edf8ff07-7e96-462d-9ad0-edc573170058)

### Reproduction

i will update if it is needed

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment] 2023-12-06 11:19
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2023-12-06 16:44 UTC
